name: Merge Surge Rules
on:
  schedule:
    - cron: '42 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: |
        # 清理工作区中的所有未跟踪文件（保留下载的文件）
        git clean -fdx

        # 下载和处理文件
        curl -o geo_as_ip_cn.txt https://raw.githubusercontent.com/DH-Teams/DH-Geo_AS_IP_CN/main/Geo_AS_IP_CN.txt
        curl -o direct.list https://raw.githubusercontent.com/001ProMax/Surge/main/Ruleset/Direct.list
        sed 's/^/IP-CIDR,/' geo_as_ip_cn.txt > geo_as_ip_cn_processed.txt
        
        # 创建目标目录并合并文件
        mkdir -p Ruleset
        cat direct.list geo_as_ip_cn_processed.txt > Ruleset/CN.txt
        
        # 配置 Git
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # 只添加 CN.txt 文件
        git add Ruleset/CN.txt
        git commit -m "Update surge rules"
        git push

        # 删除不需要的临时文件
        rm -f geo_as_ip_cn.txt geo_as_ip_cn_processed.txt direct.list
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
